FROM python:3.11.1
RUN groupadd --gid 1000 appuser \
    && useradd --uid 1000 --gid 1000 -ms /bin/bash appuser

RUN pip3 install --no-cache-dir --upgrade \
    pip \
    virtualenv

RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common

USER appuser
WORKDIR /home/appuser

COPY images /home/appuser/images
COPY app.py /home/appuser/app.py
COPY bedrock_util.py /home/appuser/bedrock_util.py
COPY requirements.txt /home/appuser/requirements.txt

ENV VIRTUAL_ENV=/home/appuser/venv
RUN virtualenv ${VIRTUAL_ENV}
RUN . ${VIRTUAL_ENV}/bin/activate && pip3 install -r requirements.txt
EXPOSE 8501

COPY run.sh /home/appuser/run.sh
CMD ["/bin/bash", "run.sh"]
